version: '3.9'

services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    depends_on:
      - discovery-service

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-service

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - discovery-service

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
      - account-service
      - customer-service
