version: '3.9'

services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - monitoring

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    depends_on:
      - discovery-service
    networks:
      - monitoring

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-service
    networks:
      - monitoring

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - discovery-service
    networks:
      - monitoring

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
      - account-service
      - customer-service
    networks:
      - monitoring

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    depends_on:
      - discovery-service
      - config-service
      - account-service
      - customer-service
      - gateway-service

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: